package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ContragentAction generated by hbm2java
 */
@Entity
@Table(name="CONTRAGENT_ACTION"
)
@XmlRootElement
public class ContragentAction  implements java.io.Serializable {


     private int id;
     private int idConrtagent;
     private String nameAction;
     private String split1;
     private String split2;
     private String firstSymvol;
     private String lastSymvol;
     private String csvKey;
     private Short csvCountColumn;
     private String sqlSvcLoad;
     private String sqlSvcUnload;
     private String svcXmlLoad;
     private String sqlXmlLoad;

    public ContragentAction() {
    }

	
    public ContragentAction(int id, int idConrtagent, String nameAction) {
        this.id = id;
        this.idConrtagent = idConrtagent;
        this.nameAction = nameAction;
    }
    public ContragentAction(int id, int idConrtagent, String nameAction, String split1, String split2, String firstSymvol, String lastSymvol, String csvKey, Short csvCountColumn, String sqlSvcLoad, String sqlSvcUnload, String svcXmlLoad, String sqlXmlLoad) {
       this.id = id;
       this.idConrtagent = idConrtagent;
       this.nameAction = nameAction;
       this.split1 = split1;
       this.split2 = split2;
       this.firstSymvol = firstSymvol;
       this.lastSymvol = lastSymvol;
       this.csvKey = csvKey;
       this.csvCountColumn = csvCountColumn;
       this.sqlSvcLoad = sqlSvcLoad;
       this.sqlSvcUnload = sqlSvcUnload;
       this.svcXmlLoad = svcXmlLoad;
       this.sqlXmlLoad = sqlXmlLoad;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ID_CONRTAGENT", nullable=false)
    public int getIdConrtagent() {
        return this.idConrtagent;
    }
    
    public void setIdConrtagent(int idConrtagent) {
        this.idConrtagent = idConrtagent;
    }

    
    @Column(name="NAME_ACTION", nullable=false, length=40)
    public String getNameAction() {
        return this.nameAction;
    }
    
    public void setNameAction(String nameAction) {
        this.nameAction = nameAction;
    }

    
    @Column(name="SPLIT_1", length=2)
    public String getSplit1() {
        return this.split1;
    }
    
    public void setSplit1(String split1) {
        this.split1 = split1;
    }

    
    @Column(name="SPLIT_2", length=2)
    public String getSplit2() {
        return this.split2;
    }
    
    public void setSplit2(String split2) {
        this.split2 = split2;
    }

    
    @Column(name="FIRST_SYMVOL", length=2)
    public String getFirstSymvol() {
        return this.firstSymvol;
    }
    
    public void setFirstSymvol(String firstSymvol) {
        this.firstSymvol = firstSymvol;
    }

    
    @Column(name="LAST_SYMVOL", length=2)
    public String getLastSymvol() {
        return this.lastSymvol;
    }
    
    public void setLastSymvol(String lastSymvol) {
        this.lastSymvol = lastSymvol;
    }

    
    @Column(name="CSV_KEY", length=1024)
    public String getCsvKey() {
        return this.csvKey;
    }
    
    public void setCsvKey(String csvKey) {
        this.csvKey = csvKey;
    }

    
    @Column(name="CSV_COUNT_COLUMN")
    public Short getCsvCountColumn() {
        return this.csvCountColumn;
    }
    
    public void setCsvCountColumn(Short csvCountColumn) {
        this.csvCountColumn = csvCountColumn;
    }

    
    @Column(name="SQL_SVC_LOAD", length=7000)
    public String getSqlSvcLoad() {
        return this.sqlSvcLoad;
    }
    
    public void setSqlSvcLoad(String sqlSvcLoad) {
        this.sqlSvcLoad = sqlSvcLoad;
    }

    
    @Column(name="SQL_SVC_UNLOAD", length=7000)
    public String getSqlSvcUnload() {
        return this.sqlSvcUnload;
    }
    
    public void setSqlSvcUnload(String sqlSvcUnload) {
        this.sqlSvcUnload = sqlSvcUnload;
    }

    
    @Column(name="SVC_XML_LOAD", length=7000)
    public String getSvcXmlLoad() {
        return this.svcXmlLoad;
    }
    
    public void setSvcXmlLoad(String svcXmlLoad) {
        this.svcXmlLoad = svcXmlLoad;
    }

    
    @Column(name="SQL_XML_LOAD", length=1024)
    public String getSqlXmlLoad() {
        return this.sqlXmlLoad;
    }
    
    public void setSqlXmlLoad(String sqlXmlLoad) {
        this.sqlXmlLoad = sqlXmlLoad;
    }




}


