package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Contragent generated by hbm2java
 */
@Entity
@Table(name="CONTRAGENT"
)
@XmlRootElement
public class Contragent  implements java.io.Serializable {


     private short id;
     private String nameContragent;
     private String agentCodeContragent;
     private String agentDeptCodeContragent;
     private String agentAgreementCodeContragent;
     private Date dateCreateContragent;
     private Date dateOfChange;
     private short idOsp;

    public Contragent() {
    }

    public Contragent(short id, String nameContragent, String agentCodeContragent, String agentDeptCodeContragent, String agentAgreementCodeContragent, Date dateCreateContragent, Date dateOfChange, short idOsp) {
       this.id = id;
       this.nameContragent = nameContragent;
       this.agentCodeContragent = agentCodeContragent;
       this.agentDeptCodeContragent = agentDeptCodeContragent;
       this.agentAgreementCodeContragent = agentAgreementCodeContragent;
       this.dateCreateContragent = dateCreateContragent;
       this.dateOfChange = dateOfChange;
       this.idOsp = idOsp;
    }
   
    @Id 
    @Column(name="ID", unique=true, nullable=false,insertable = true)
    public short getId() {
        return this.id;
    }  
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="NAME_CONTRAGENT", nullable=false, length=50)
    public String getNameContragent() {
        return this.nameContragent;
    }
    
    public void setNameContragent(String nameContragent) {
        this.nameContragent = nameContragent;
    }

    
    @Column(name="AGENT_CODE_CONTRAGENT", nullable=false, length=50)
    public String getAgentCodeContragent() {
        return this.agentCodeContragent;
    }
    
    public void setAgentCodeContragent(String agentCodeContragent) {
        this.agentCodeContragent = agentCodeContragent;
    }

    
    @Column(name="AGENT_DEPT_CODE_CONTRAGENT", nullable=false, length=50)
    public String getAgentDeptCodeContragent() {
        return this.agentDeptCodeContragent;
    }
    
    public void setAgentDeptCodeContragent(String agentDeptCodeContragent) {
        this.agentDeptCodeContragent = agentDeptCodeContragent;
    }

    
    @Column(name="AGENT_AGREEMENT_CODE_CONTRAGENT", nullable=false, length=50)
    public String getAgentAgreementCodeContragent() {
        return this.agentAgreementCodeContragent;
    }
    
    public void setAgentAgreementCodeContragent(String agentAgreementCodeContragent) {
        this.agentAgreementCodeContragent = agentAgreementCodeContragent;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATE_CONTRAGENT", nullable=true, length=10)
    public Date getDateCreateContragent() {
        return this.dateCreateContragent;
    }
    
    public void setDateCreateContragent(Date dateCreateContragent) {
        this.dateCreateContragent = dateCreateContragent;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_CHANGE", nullable=true, length=10)
    public Date getDateOfChange() {
        return this.dateOfChange;
    }
    
    public void setDateOfChange(Date dateOfChange) {
        this.dateOfChange = dateOfChange;
    }

    
    @Column(name="ID_OSP", nullable=false)
    public short getIdOsp() {
        return this.idOsp;
    }
    
    public void setIdOsp(short idOsp) {
        this.idOsp = idOsp;
    }




}


