package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Osp generated by hbm2java
 */
@Entity
@Table(name="OSP"
)
@XmlRootElement
public class Osp  implements java.io.Serializable {


     private short id;
     private String nameOsp;
     private String ipOsp;
     private String passwordOsp;
     private String loginOsp;
     private String aliasesOsp;
     private String vkspOsp;
     private Date dateCreateOsp;
     private Date dateOfChange;

    public Osp() {
    }

	
    public Osp(short id, String nameOsp, String ipOsp, String passwordOsp, String loginOsp, String aliasesOsp, String vkspOsp) {
        this.id = id;
        this.nameOsp = nameOsp;
        this.ipOsp = ipOsp;
        this.passwordOsp = passwordOsp;
        this.loginOsp = loginOsp;
        this.aliasesOsp = aliasesOsp;
        this.vkspOsp = vkspOsp;
    }
    public Osp(short id, String nameOsp, String ipOsp, String passwordOsp, String loginOsp, String aliasesOsp, String vkspOsp, Date dateCreateOsp, Date dateOfChange) {
       this.id = id;
       this.nameOsp = nameOsp;
       this.ipOsp = ipOsp;
       this.passwordOsp = passwordOsp;
       this.loginOsp = loginOsp;
       this.aliasesOsp = aliasesOsp;
       this.vkspOsp = vkspOsp;
       this.dateCreateOsp = dateCreateOsp;
       this.dateOfChange = dateOfChange;
    }
   
    @Id  
    @Column(name="ID", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="NAME_OSP", nullable=false, length=25)
    public String getNameOsp() {
        return this.nameOsp;
    }
    
    public void setNameOsp(String nameOsp) {
        this.nameOsp = nameOsp;
    }

    
    @Column(name="IP_OSP", nullable=false, length=16)
    public String getIpOsp() {
        return this.ipOsp;
    }
    
    public void setIpOsp(String ipOsp) {
        this.ipOsp = ipOsp;
    }

    
    @Column(name="PASSWORD_OSP", nullable=false, length=25)
    public String getPasswordOsp() {
        return this.passwordOsp;
    }
    
    public void setPasswordOsp(String passwordOsp) {
        this.passwordOsp = passwordOsp;
    }

    
    @Column(name="LOGIN_OSP", nullable=false, length=25)
    public String getLoginOsp() {
        return this.loginOsp;
    }
    
    public void setLoginOsp(String loginOsp) {
        this.loginOsp = loginOsp;
    }

    
    @Column(name="ALIASES_OSP", nullable=false, length=25)
    public String getAliasesOsp() {
        return this.aliasesOsp;
    }
    
    public void setAliasesOsp(String aliasesOsp) {
        this.aliasesOsp = aliasesOsp;
    }

    
    @Column(name="VKSP_OSP", nullable=false, length=30)
    public String getVkspOsp() {
        return this.vkspOsp;
    }
    
    public void setVkspOsp(String vkspOsp) {
        this.vkspOsp = vkspOsp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATE_OSP", length=10)
    public Date getDateCreateOsp() {
        return this.dateCreateOsp;
    }
    
    public void setDateCreateOsp(Date dateCreateOsp) {
        this.dateCreateOsp = dateCreateOsp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_CHANGE", length=10)
    public Date getDateOfChange() {
        return this.dateOfChange;
    }
    
    public void setDateOfChange(Date dateOfChange) {
        this.dateOfChange = dateOfChange;
    }




}


