package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * OspContragent generated by hbm2java
 */
@Entity
@Table(name="OSP_CONTRAGENT"
)
@XmlRootElement
public class OspContragent  implements java.io.Serializable {


     private OspContragentId id;

    public OspContragent() {
    }

    public OspContragent(OspContragentId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOsp", column=@Column(name="ID_OSP", nullable=false) ), 
        @AttributeOverride(name="idContragent", column=@Column(name="ID_CONTRAGENT", nullable=false) ) } )
    public OspContragentId getId() {
        return this.id;
    }
    
    public void setId(OspContragentId id) {
        this.id = id;
    }




}


