package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OspContragentId generated by hbm2java
 */
@Embeddable
public class OspContragentId  implements java.io.Serializable {


     private int idOsp;
     private int idContragent;

    public OspContragentId() {
    }

    public OspContragentId(int idOsp, int idContragent) {
       this.idOsp = idOsp;
       this.idContragent = idContragent;
    }
   


    @Column(name="ID_OSP", nullable=false)
    public int getIdOsp() {
        return this.idOsp;
    }
    
    public void setIdOsp(int idOsp) {
        this.idOsp = idOsp;
    }


    @Column(name="ID_CONTRAGENT", nullable=false)
    public int getIdContragent() {
        return this.idContragent;
    }
    
    public void setIdContragent(int idContragent) {
        this.idContragent = idContragent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OspContragentId) ) return false;
		 OspContragentId castOther = ( OspContragentId ) other; 
         
		 return (this.getIdOsp()==castOther.getIdOsp())
 && (this.getIdContragent()==castOther.getIdContragent());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOsp();
         result = 37 * result + this.getIdContragent();
         return result;
   }   


}


