package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SysLabelLevel generated by hbm2java
 */
@Entity
@Table(name="SYS_LABEL_LEVEL"
)
@XmlRootElement
public class SysLabelLevel  implements java.io.Serializable {


     private int sllvId;
     private String sllvCaption;

    public SysLabelLevel() {
    }

    public SysLabelLevel(int sllvId, String sllvCaption) {
       this.sllvId = sllvId;
       this.sllvCaption = sllvCaption;
    }
   
     @Id 

    
    @Column(name="SLLV_ID", unique=true, nullable=false)
    public int getSllvId() {
        return this.sllvId;
    }
    
    public void setSllvId(int sllvId) {
        this.sllvId = sllvId;
    }

    
    @Column(name="SLLV_CAPTION", nullable=false, length=80)
    public String getSllvCaption() {
        return this.sllvCaption;
    }
    
    public void setSllvCaption(String sllvCaption) {
        this.sllvCaption = sllvCaption;
    }




}


