package Database.dbClassesEntity;
// Generated 06.06.2016 13:06:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SysUsers generated by hbm2java
 */
@Entity
@Table(name="SYS_USERS"
)
@XmlRootElement
public class SysUsers  implements java.io.Serializable {


     private short id;
     private String loginUser;
     private String passwordUser;
     private int suserId;

    public SysUsers() {
    }

    public SysUsers(short id, String loginUser, String passwordUser, int suserId) {
       this.id = id;
       this.loginUser = loginUser;
       this.passwordUser = passwordUser;
       this.suserId = suserId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    
    @Column(name="LOGIN_USER", nullable=false, length=10)
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }

    
    @Column(name="PASSWORD_USER", nullable=false, length=10)
    public String getPasswordUser() {
        return this.passwordUser;
    }
    
    public void setPasswordUser(String passwordUser) {
        this.passwordUser = passwordUser;
    }

    
    @Column(name="SUSER_ID", nullable=false)
    public int getSuserId() {
        return this.suserId;
    }
    
    public void setSuserId(int suserId) {
        this.suserId = suserId;
    }




}


